remote_theme: mmistakes/minimal-mistakes
title: Julia Gonzalez homepage
description: Bookmark this to keep an eye on my project updates!

description: "Desarrollador"
author:
  name: "Julia Gonz√°lez"
  email: "juliagon@unex.es"
